config/routes.rb
Rails.application.routes.draw do

  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController



  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/destroy.html.erb
<a data-turbo-method="delete"
   data-turbo-confirm="Are you sure?">
   Delete
</a>

app/views/tasks/edit.html.erb
<h1>Please edit a Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%> <br>
  <%= f.label :details %>
  <%= f.text_field :details %> <br>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Here are all your tasks</h1>

<ul>
  <% @tasks.each do |task| %>
   <li><%= link_to task.title, task_path(task.id) %></li>
  <% end %>
</ul>

<h4>Add a new task</h4>
<%= link_to 'Add a new task',  new_task_path %>

app/views/tasks/new.html.erb
<h1>Please add a Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title%> <br>
  <%= f.label :details %>
  <%= f.text_field :details %> <br>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

<p><%= link_to 'Main Page', tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<h2><%= @task.details %></h2>
 <% if @task.completed === true %>
  <p>Your task is completed</p>
 <% else %>
   <p>Your task is not completed</p>
 <% end %>

<%= link_to 'Back to the list', tasks_path %> <br>
<%= link_to 'Edit a list', edit_path(@task.id) %> <br>
<%= link_to "Delete", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>